"""add_medication_symptom_health_event_tables

Revision ID: 1fb39c2bd34d
Revises: 0987acfbec4a
Create Date: 2026-01-15 15:28:03.608173

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1fb39c2bd34d'
down_revision: Union[str, Sequence[str], None] = '0987acfbec4a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gd2502_health_event_records',
    sa.Column('id', sa.String(length=50), nullable=False, comment='记录ID（ULID）'),
    sa.Column('user_id', sa.String(length=50), nullable=False, comment='用户ID'),
    sa.Column('event_type', sa.String(length=100), nullable=False, comment='健康事件类型（如：少吃盐、运动、心情放松、睡眠良好）'),
    sa.Column('check_in_time', sa.DateTime(timezone=True), nullable=True, comment='打卡时间（可选，不提供则使用当前时间）'),
    sa.Column('notes', sa.Text(), nullable=True, comment='备注（可选）'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间（自动生成）'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True, comment='更新时间（自动更新）'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gd2502_health_event_records_check_in_time'), 'gd2502_health_event_records', ['check_in_time'], unique=False)
    op.create_index(op.f('ix_gd2502_health_event_records_id'), 'gd2502_health_event_records', ['id'], unique=False)
    op.create_index(op.f('ix_gd2502_health_event_records_user_id'), 'gd2502_health_event_records', ['user_id'], unique=False)
    op.create_table('gd2502_medication_records',
    sa.Column('id', sa.String(length=50), nullable=False, comment='记录ID（ULID）'),
    sa.Column('user_id', sa.String(length=50), nullable=False, comment='用户ID'),
    sa.Column('medication_name', sa.String(length=200), nullable=False, comment='药品名称（冗余字段，便于查询和显示）'),
    sa.Column('medication_time', sa.DateTime(timezone=True), nullable=True, comment='用药时间（可选，不提供则使用当前时间）'),
    sa.Column('dosage', sa.Integer(), nullable=False, comment='每次服用剂量（如：2）'),
    sa.Column('dosage_unit', sa.String(length=50), nullable=False, comment='剂量单位（如：片、粒、ml、mg等）'),
    sa.Column('notes', sa.Text(), nullable=True, comment='备注（可选）'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间（自动生成）'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True, comment='更新时间（自动更新）'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gd2502_medication_records_id'), 'gd2502_medication_records', ['id'], unique=False)
    op.create_index(op.f('ix_gd2502_medication_records_medication_time'), 'gd2502_medication_records', ['medication_time'], unique=False)
    op.create_index(op.f('ix_gd2502_medication_records_user_id'), 'gd2502_medication_records', ['user_id'], unique=False)
    op.create_table('gd2502_symptom_records',
    sa.Column('id', sa.String(length=50), nullable=False, comment='记录ID（ULID）'),
    sa.Column('user_id', sa.String(length=50), nullable=False, comment='用户ID'),
    sa.Column('symptom_name', sa.String(length=200), nullable=False, comment='症状名'),
    sa.Column('record_time', sa.DateTime(timezone=True), nullable=True, comment='症状记录时间（可选，不提供则使用当前时间）'),
    sa.Column('recovery_status', sa.String(length=20), nullable=False, comment='是否已经痊愈（枚举：新记录、老记录、痊愈）'),
    sa.Column('notes', sa.Text(), nullable=True, comment='备注（可选）'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间（自动生成）'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True, comment='更新时间（自动更新）'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gd2502_symptom_records_id'), 'gd2502_symptom_records', ['id'], unique=False)
    op.create_index(op.f('ix_gd2502_symptom_records_record_time'), 'gd2502_symptom_records', ['record_time'], unique=False)
    op.create_index(op.f('ix_gd2502_symptom_records_user_id'), 'gd2502_symptom_records', ['user_id'], unique=False)
    op.alter_column('gd2502_session_cache', 'id',
               existing_type=sa.VARCHAR(length=200),
               comment='Session ID（直接使用session_id）',
               existing_comment='Session ID',
               existing_nullable=False)
    op.alter_column('gd2502_session_cache', 'data_info',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='Session上下文字典数据（JSON格式）',
               existing_comment='Session上下文字典数据',
               existing_nullable=False)
    op.alter_column('gd2502_token_cache', 'id',
               existing_type=sa.VARCHAR(length=200),
               comment='Token ID（直接使用token_id/user_id）',
               existing_comment='Token ID（即user_id）',
               existing_nullable=False)
    op.alter_column('gd2502_token_cache', 'data_info',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='UserInfo对象序列化数据（JSON格式）',
               existing_comment='UserInfo对象序列化数据',
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('gd2502_token_cache', 'data_info',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='UserInfo对象序列化数据',
               existing_comment='UserInfo对象序列化数据（JSON格式）',
               existing_nullable=False)
    op.alter_column('gd2502_token_cache', 'id',
               existing_type=sa.VARCHAR(length=200),
               comment='Token ID（即user_id）',
               existing_comment='Token ID（直接使用token_id/user_id）',
               existing_nullable=False)
    op.alter_column('gd2502_session_cache', 'data_info',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='Session上下文字典数据',
               existing_comment='Session上下文字典数据（JSON格式）',
               existing_nullable=False)
    op.alter_column('gd2502_session_cache', 'id',
               existing_type=sa.VARCHAR(length=200),
               comment='Session ID',
               existing_comment='Session ID（直接使用session_id）',
               existing_nullable=False)
    op.drop_index(op.f('ix_gd2502_symptom_records_user_id'), table_name='gd2502_symptom_records')
    op.drop_index(op.f('ix_gd2502_symptom_records_record_time'), table_name='gd2502_symptom_records')
    op.drop_index(op.f('ix_gd2502_symptom_records_id'), table_name='gd2502_symptom_records')
    op.drop_table('gd2502_symptom_records')
    op.drop_index(op.f('ix_gd2502_medication_records_user_id'), table_name='gd2502_medication_records')
    op.drop_index(op.f('ix_gd2502_medication_records_medication_time'), table_name='gd2502_medication_records')
    op.drop_index(op.f('ix_gd2502_medication_records_id'), table_name='gd2502_medication_records')
    op.drop_table('gd2502_medication_records')
    op.drop_index(op.f('ix_gd2502_health_event_records_user_id'), table_name='gd2502_health_event_records')
    op.drop_index(op.f('ix_gd2502_health_event_records_id'), table_name='gd2502_health_event_records')
    op.drop_index(op.f('ix_gd2502_health_event_records_check_in_time'), table_name='gd2502_health_event_records')
    op.drop_table('gd2502_health_event_records')
    # ### end Alembic commands ###
