"""add ai_response field to embedding_records

Revision ID: 4d076248e1b9
Revises: 9a6d8edb7942
Create Date: 2026-01-23 13:55:05.672779

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4d076248e1b9'
down_revision: Union[str, Sequence[str], None] = '9a6d8edb7942'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gd2502_embedding_records', sa.Column('ai_response', sa.Text(), nullable=True, comment='AI回复内容（来自原始表的new_session_response）'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('gd2502_embedding_records', 'ai_response')
    # ### end Alembic commands ###
