"""add embedding_value field to embedding_records

Revision ID: 52d7e028101e
Revises: 4d076248e1b9
Create Date: 2026-01-23 14:14:31.679722

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# 导入 pgvector 支持
try:
    import pgvector
    from pgvector.sqlalchemy import Vector
    HAS_PGVECTOR = True
except ImportError:
    HAS_PGVECTOR = False
    # 如果 pgvector 不可用，创建一个占位符类型
    class Vector:
        pass


# revision identifiers, used by Alembic.
revision: str = '52d7e028101e'
down_revision: Union[str, Sequence[str], None] = '4d076248e1b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    if HAS_PGVECTOR:
        op.add_column('gd2502_embedding_records', sa.Column('embedding_value', pgvector.sqlalchemy.vector.VECTOR(dim=2048), nullable=True, comment='Embedding向量值（2048维，由embedding_node生成）'))
    else:
        # 如果 pgvector 不可用，使用 Text 类型（不推荐用于生产）
        op.add_column('gd2502_embedding_records', sa.Column('embedding_value', sa.Text(), nullable=True, comment='Embedding向量值（2048维，由embedding_node生成）'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('gd2502_embedding_records', 'embedding_value')
    # ### end Alembic commands ###
