"""将向量维度更新为 768

Revision ID: 7a7434ef5a78
Revises: fb605d274d89
Create Date: 2025-12-11 16:17:45.420661

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector
import pgvector.sqlalchemy


# revision identifiers, used by Alembic.
revision: str = '7a7434ef5a78'
down_revision: Union[str, Sequence[str], None] = 'fb605d274d89'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """升级数据库架构。"""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('knowledge_base', 'embedding',
               existing_type=pgvector.sqlalchemy.vector.VECTOR(dim=1536),
               type_=pgvector.sqlalchemy.vector.VECTOR(dim=768),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """降级数据库架构。"""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('knowledge_base', 'embedding',
               existing_type=pgvector.sqlalchemy.vector.VECTOR(dim=768),
               type_=pgvector.sqlalchemy.vector.VECTOR(dim=1536),
               existing_nullable=False)
    # ### end Alembic commands ###
