"""add embedding_records table

Revision ID: 9a6d8edb7942
Revises: 2ab45c6d8e9f
Create Date: 2026-01-23 11:47:51.056817

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# 导入 pgvector 支持
try:
    import pgvector
    from pgvector.sqlalchemy import Vector
    HAS_PGVECTOR = True
except ImportError:
    HAS_PGVECTOR = False
    # 如果 pgvector 不可用，创建一个占位符类型
    class Vector:
        pass


# revision identifiers, used by Alembic.
revision: str = '9a6d8edb7942'
down_revision: Union[str, Sequence[str], None] = '2ab45c6d8e9f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gd2502_embedding_records',
    sa.Column('id', sa.String(length=50), nullable=False, comment='记录ID（ULID）'),
    sa.Column('scene_summary', sa.Text(), nullable=False, comment='场景摘要'),
    sa.Column('optimization_question', sa.Text(), nullable=False, comment='优化后的问题'),
    sa.Column('input_tags', sa.Text(), nullable=True, comment='输入标签（JSON数组字符串）'),
    sa.Column('response_tags', sa.Text(), nullable=True, comment='响应标签（JSON数组字符串）'),
    sa.Column('message_id', sa.String(length=100), nullable=True, comment='消息ID（关联数据源）'),
    sa.Column('version', sa.Integer(), nullable=False, comment='版本号（从0开始递增）'),
    sa.Column('is_published', sa.Boolean(), nullable=False, comment='是否发布'),
    sa.Column('source_table_name', sa.String(length=200), nullable=True, comment='数据来源表名'),
    sa.Column('source_record_id', sa.String(length=50), nullable=True, comment='数据来源记录ID'),
    sa.Column('generation_status', sa.Integer(), nullable=False, comment='生成状态（0=进行中，1=成功，-1=失败）'),
    sa.Column('failure_reason', sa.Text(), nullable=True, comment='失败原因（包含异常堆栈信息）'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间（自动生成）'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True, comment='更新时间（自动更新）'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gd2502_embedding_records_id'), 'gd2502_embedding_records', ['id'], unique=False)
    op.create_index(op.f('ix_gd2502_embedding_records_message_id'), 'gd2502_embedding_records', ['message_id'], unique=False)
    
    # 以下是对其他表的修改（可能是之前未提交的变更）
    # 如果这些变更不需要，可以注释掉
    if HAS_PGVECTOR:
        op.alter_column('gd2502_greeting_examples', 'embedding',
                   existing_type=pgvector.sqlalchemy.vector.VECTOR(dim=768),
                   nullable=False,
                   existing_comment='向量（768维，使用moka-ai/m3e-base）')
        op.drop_index(op.f('gd2502_greeting_examples_embedding_idx'), table_name='gd2502_greeting_examples', postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_using='hnsw')
        op.drop_constraint(op.f('gd2502_popular_science_article_article_material_id_key'), 'gd2502_popular_science_article', type_='unique')
        op.drop_index(op.f('gd2502_popular_science_article_embedding_idx'), table_name='gd2502_popular_science_article', postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_using='hnsw')
        op.drop_index(op.f('gd2502_qa_examples_embedding_idx'), table_name='gd2502_qa_examples', postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_using='hnsw')
        op.alter_column('gd2502_query_examples', 'embedding',
                   existing_type=pgvector.sqlalchemy.vector.VECTOR(dim=768),
                   nullable=False,
                   existing_comment='向量（768维，使用moka-ai/m3e-base）')
        op.drop_index(op.f('gd2502_query_examples_embedding_idx'), table_name='gd2502_query_examples', postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_using='hnsw')
        op.alter_column('gd2502_record_examples', 'embedding',
                   existing_type=pgvector.sqlalchemy.vector.VECTOR(dim=768),
                   nullable=False,
                   existing_comment='向量（768维，使用moka-ai/m3e-base）')
        op.drop_index(op.f('gd2502_record_examples_embedding_idx'), table_name='gd2502_record_examples', postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_using='hnsw')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('gd2502_record_examples_embedding_idx'), 'gd2502_record_examples', ['embedding'], unique=False, postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_using='hnsw')
    op.alter_column('gd2502_record_examples', 'embedding',
               existing_type=pgvector.sqlalchemy.vector.VECTOR(dim=768),
               nullable=True,
               existing_comment='向量（768维，使用moka-ai/m3e-base）')
    op.create_index(op.f('gd2502_query_examples_embedding_idx'), 'gd2502_query_examples', ['embedding'], unique=False, postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_using='hnsw')
    op.alter_column('gd2502_query_examples', 'embedding',
               existing_type=pgvector.sqlalchemy.vector.VECTOR(dim=768),
               nullable=True,
               existing_comment='向量（768维，使用moka-ai/m3e-base）')
    op.create_index(op.f('gd2502_qa_examples_embedding_idx'), 'gd2502_qa_examples', ['embedding'], unique=False, postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_using='hnsw')
    op.create_index(op.f('gd2502_popular_science_article_embedding_idx'), 'gd2502_popular_science_article', ['embedding'], unique=False, postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_using='hnsw')
    op.create_unique_constraint(op.f('gd2502_popular_science_article_article_material_id_key'), 'gd2502_popular_science_article', ['article_material_id'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('gd2502_greeting_examples_embedding_idx'), 'gd2502_greeting_examples', ['embedding'], unique=False, postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_using='hnsw')
    op.alter_column('gd2502_greeting_examples', 'embedding',
               existing_type=pgvector.sqlalchemy.vector.VECTOR(dim=768),
               nullable=True,
               existing_comment='向量（768维，使用moka-ai/m3e-base）')
    op.drop_index(op.f('ix_gd2502_embedding_records_message_id'), table_name='gd2502_embedding_records')
    op.drop_index(op.f('ix_gd2502_embedding_records_id'), table_name='gd2502_embedding_records')
    op.drop_table('gd2502_embedding_records')
    # ### end Alembic commands ###
