"""init schema

Revision ID: a9778dac2e2f
Revises: 
Create Date: 2025-12-17 17:48:59.600460

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a9778dac2e2f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('biz_agent_appointments',
    sa.Column('id', sa.String(length=50), nullable=False, comment='预约ID'),
    sa.Column('user_id', sa.String(length=50), nullable=False, comment='用户ID'),
    sa.Column('department', sa.String(length=100), nullable=False, comment='科室'),
    sa.Column('doctor_name', sa.String(length=100), nullable=True, comment='医生姓名'),
    sa.Column('appointment_time', sa.DateTime(timezone=True), nullable=False, comment='预约时间'),
    sa.Column('status', sa.Enum('PENDING', 'CONFIRMED', 'COMPLETED', 'CANCELLED', name='appointmentstatus'), nullable=True, comment='预约状态'),
    sa.Column('notes', sa.Text(), nullable=True, comment='备注'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='更新时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_biz_agent_appointments_appointment_time'), 'biz_agent_appointments', ['appointment_time'], unique=False)
    op.create_index(op.f('ix_biz_agent_appointments_id'), 'biz_agent_appointments', ['id'], unique=False)
    op.create_index(op.f('ix_biz_agent_appointments_user_id'), 'biz_agent_appointments', ['user_id'], unique=False)
    op.create_table('biz_agent_blood_pressure_records',
    sa.Column('id', sa.String(length=50), nullable=False, comment='记录ID'),
    sa.Column('user_id', sa.String(length=50), nullable=False, comment='用户ID'),
    sa.Column('systolic', sa.Integer(), nullable=False, comment='收缩压（高压）'),
    sa.Column('diastolic', sa.Integer(), nullable=False, comment='舒张压（低压）'),
    sa.Column('heart_rate', sa.Integer(), nullable=True, comment='心率'),
    sa.Column('record_time', sa.DateTime(timezone=True), nullable=True, comment='记录时间（可为空，默认NULL）'),
    sa.Column('notes', sa.Text(), nullable=True, comment='备注'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True, comment='创建时间（可为空，默认NULL）'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True, comment='更新时间（可为空，默认NULL）'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_biz_agent_blood_pressure_records_id'), 'biz_agent_blood_pressure_records', ['id'], unique=False)
    op.create_index(op.f('ix_biz_agent_blood_pressure_records_record_time'), 'biz_agent_blood_pressure_records', ['record_time'], unique=False)
    op.create_index(op.f('ix_biz_agent_blood_pressure_records_user_id'), 'biz_agent_blood_pressure_records', ['user_id'], unique=False)
    op.create_table('biz_agent_llm_call_logs',
    sa.Column('id', sa.String(length=50), nullable=False, comment='主键ID'),
    sa.Column('call_id', sa.String(length=64), nullable=False, comment='调用唯一ID'),
    sa.Column('trace_id', sa.String(length=64), nullable=True, comment='链路追踪ID'),
    sa.Column('session_id', sa.String(length=64), nullable=True, comment='会话ID'),
    sa.Column('conversation_id', sa.String(length=64), nullable=True, comment='对话ID'),
    sa.Column('user_id', sa.String(length=50), nullable=True, comment='用户ID'),
    sa.Column('agent_key', sa.String(length=100), nullable=True, comment='智能体标识'),
    sa.Column('model', sa.String(length=100), nullable=False, comment='模型名称'),
    sa.Column('temperature', sa.Numeric(precision=4, scale=2), nullable=True, comment='温度参数'),
    sa.Column('top_p', sa.Numeric(precision=4, scale=2), nullable=True, comment='Top-p 参数'),
    sa.Column('max_tokens', sa.Integer(), nullable=True, comment='最大输出 tokens'),
    sa.Column('prompt_tokens', sa.Integer(), nullable=True, comment='提示 tokens 消耗'),
    sa.Column('completion_tokens', sa.Integer(), nullable=True, comment='生成 tokens 消耗'),
    sa.Column('total_tokens', sa.Integer(), nullable=True, comment='总 tokens 消耗'),
    sa.Column('latency_ms', sa.Integer(), nullable=True, comment='耗时（毫秒）'),
    sa.Column('success', sa.Boolean(), nullable=True, comment='是否成功'),
    sa.Column('error_code', sa.String(length=50), nullable=True, comment='错误码'),
    sa.Column('error_message', sa.Text(), nullable=True, comment='错误信息'),
    sa.Column('prompt_snapshot', sa.Text(), nullable=True, comment='提示词快照（截断存储）'),
    sa.Column('response_snapshot', sa.Text(), nullable=True, comment='响应快照（截断存储）'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='创建时间'),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True, comment='完成时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_biz_agent_llm_call_logs_agent_key'), 'biz_agent_llm_call_logs', ['agent_key'], unique=False)
    op.create_index(op.f('ix_biz_agent_llm_call_logs_call_id'), 'biz_agent_llm_call_logs', ['call_id'], unique=False)
    op.create_index(op.f('ix_biz_agent_llm_call_logs_id'), 'biz_agent_llm_call_logs', ['id'], unique=False)
    op.create_index(op.f('ix_biz_agent_llm_call_logs_session_id'), 'biz_agent_llm_call_logs', ['session_id'], unique=False)
    op.create_index(op.f('ix_biz_agent_llm_call_logs_trace_id'), 'biz_agent_llm_call_logs', ['trace_id'], unique=False)
    op.create_index(op.f('ix_biz_agent_llm_call_logs_user_id'), 'biz_agent_llm_call_logs', ['user_id'], unique=False)
    op.create_table('biz_agent_llm_call_messages',
    sa.Column('id', sa.String(length=50), nullable=False, comment='主键ID'),
    sa.Column('call_id', sa.String(length=64), nullable=False, comment='调用唯一ID'),
    sa.Column('role', sa.String(length=20), nullable=False, comment='角色（system/human/assistant/tool）'),
    sa.Column('content', sa.Text(), nullable=False, comment='消息内容'),
    sa.Column('token_estimate', sa.Integer(), nullable=True, comment='token 粗略估算'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='创建时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_biz_agent_llm_call_messages_call_id'), 'biz_agent_llm_call_messages', ['call_id'], unique=False)
    op.create_index(op.f('ix_biz_agent_llm_call_messages_id'), 'biz_agent_llm_call_messages', ['id'], unique=False)
    op.create_table('biz_agent_users',
    sa.Column('id', sa.String(length=50), nullable=False, comment='用户ID'),
    sa.Column('username', sa.String(length=100), nullable=False, comment='用户名'),
    sa.Column('phone', sa.String(length=20), nullable=True, comment='手机号'),
    sa.Column('email', sa.String(length=100), nullable=True, comment='邮箱'),
    sa.Column('is_active', sa.Boolean(), nullable=True, comment='是否激活'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='更新时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_biz_agent_users_id'), 'biz_agent_users', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_biz_agent_users_id'), table_name='biz_agent_users')
    op.drop_table('biz_agent_users')
    op.drop_index(op.f('ix_biz_agent_llm_call_messages_id'), table_name='biz_agent_llm_call_messages')
    op.drop_index(op.f('ix_biz_agent_llm_call_messages_call_id'), table_name='biz_agent_llm_call_messages')
    op.drop_table('biz_agent_llm_call_messages')
    op.drop_index(op.f('ix_biz_agent_llm_call_logs_user_id'), table_name='biz_agent_llm_call_logs')
    op.drop_index(op.f('ix_biz_agent_llm_call_logs_trace_id'), table_name='biz_agent_llm_call_logs')
    op.drop_index(op.f('ix_biz_agent_llm_call_logs_session_id'), table_name='biz_agent_llm_call_logs')
    op.drop_index(op.f('ix_biz_agent_llm_call_logs_id'), table_name='biz_agent_llm_call_logs')
    op.drop_index(op.f('ix_biz_agent_llm_call_logs_call_id'), table_name='biz_agent_llm_call_logs')
    op.drop_index(op.f('ix_biz_agent_llm_call_logs_agent_key'), table_name='biz_agent_llm_call_logs')
    op.drop_table('biz_agent_llm_call_logs')
    op.drop_index(op.f('ix_biz_agent_blood_pressure_records_user_id'), table_name='biz_agent_blood_pressure_records')
    op.drop_index(op.f('ix_biz_agent_blood_pressure_records_record_time'), table_name='biz_agent_blood_pressure_records')
    op.drop_index(op.f('ix_biz_agent_blood_pressure_records_id'), table_name='biz_agent_blood_pressure_records')
    op.drop_table('biz_agent_blood_pressure_records')
    op.drop_index(op.f('ix_biz_agent_appointments_user_id'), table_name='biz_agent_appointments')
    op.drop_index(op.f('ix_biz_agent_appointments_id'), table_name='biz_agent_appointments')
    op.drop_index(op.f('ix_biz_agent_appointments_appointment_time'), table_name='biz_agent_appointments')
    op.drop_table('biz_agent_appointments')
    # ### end Alembic commands ###

