"""add health_event medication symptom tables

Revision ID: b65f9b55f4e3
Revises: a9778dac2e2f
Create Date: 2025-12-19 17:04:50.075619

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b65f9b55f4e3'
down_revision: Union[str, None] = 'a9778dac2e2f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # 创建健康事件记录表
    op.create_table('biz_agent_health_event_records',
    sa.Column('id', sa.String(length=50), nullable=False, comment='记录ID'),
    sa.Column('user_id', sa.String(length=50), nullable=False, comment='用户ID'),
    sa.Column('event_type', sa.String(length=100), nullable=False, comment='事件类型（如：体检、检查、手术、疫苗接种等）'),
    sa.Column('event_name', sa.String(length=200), nullable=False, comment='事件名称（如：年度体检、血常规检查等）'),
    sa.Column('event_date', sa.DateTime(timezone=True), nullable=True, comment='事件日期（可为空，默认NULL）'),
    sa.Column('location', sa.String(length=200), nullable=True, comment='发生地点（如：医院名称）'),
    sa.Column('description', sa.Text(), nullable=True, comment='事件描述'),
    sa.Column('notes', sa.Text(), nullable=True, comment='备注'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True, comment='创建时间（可为空，默认NULL）'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True, comment='更新时间（可为空，默认NULL）'),
    sa.PrimaryKeyConstraint('id', name=op.f('biz_agent_health_event_records_pkey'))
    )
    op.create_index(op.f('ix_biz_agent_health_event_records_id'), 'biz_agent_health_event_records', ['id'], unique=False)
    op.create_index(op.f('ix_biz_agent_health_event_records_user_id'), 'biz_agent_health_event_records', ['user_id'], unique=False)
    op.create_index(op.f('ix_biz_agent_health_event_records_event_date'), 'biz_agent_health_event_records', ['event_date'], unique=False)
    
    # 创建用药记录表
    op.create_table('biz_agent_medication_records',
    sa.Column('id', sa.String(length=50), nullable=False, comment='记录ID'),
    sa.Column('user_id', sa.String(length=50), nullable=False, comment='用户ID'),
    sa.Column('medication_name', sa.String(length=200), nullable=False, comment='药物名称'),
    sa.Column('dosage', sa.String(length=100), nullable=False, comment='剂量（如：10mg、1片等）'),
    sa.Column('frequency', sa.String(length=100), nullable=False, comment='用药频率（如：每日一次、每日三次等）'),
    sa.Column('start_date', sa.DateTime(timezone=True), nullable=True, comment='开始日期（可为空，默认NULL）'),
    sa.Column('end_date', sa.DateTime(timezone=True), nullable=True, comment='结束日期（可为空，默认NULL）'),
    sa.Column('doctor_name', sa.String(length=100), nullable=True, comment='开药医生'),
    sa.Column('purpose', sa.String(length=200), nullable=True, comment='用药目的（如：降血压、治疗感冒等）'),
    sa.Column('notes', sa.Text(), nullable=True, comment='备注'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True, comment='创建时间（可为空，默认NULL）'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True, comment='更新时间（可为空，默认NULL）'),
    sa.PrimaryKeyConstraint('id', name=op.f('biz_agent_medication_records_pkey'))
    )
    op.create_index(op.f('ix_biz_agent_medication_records_id'), 'biz_agent_medication_records', ['id'], unique=False)
    op.create_index(op.f('ix_biz_agent_medication_records_user_id'), 'biz_agent_medication_records', ['user_id'], unique=False)
    op.create_index(op.f('ix_biz_agent_medication_records_start_date'), 'biz_agent_medication_records', ['start_date'], unique=False)
    
    # 创建症状记录表
    op.create_table('biz_agent_symptom_records',
    sa.Column('id', sa.String(length=50), nullable=False, comment='记录ID'),
    sa.Column('user_id', sa.String(length=50), nullable=False, comment='用户ID'),
    sa.Column('symptom_name', sa.String(length=200), nullable=False, comment='症状名称（如：头痛、发热、咳嗽等）'),
    sa.Column('severity', sa.String(length=50), nullable=True, comment='严重程度（如：轻微、中等、严重）'),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=True, comment='开始时间（可为空，默认NULL）'),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=True, comment='结束时间（可为空，默认NULL）'),
    sa.Column('duration', sa.String(length=100), nullable=True, comment='持续时间（如：2小时、3天等）'),
    sa.Column('location', sa.String(length=200), nullable=True, comment='症状部位（如：头部、胸部等）'),
    sa.Column('description', sa.Text(), nullable=True, comment='症状描述'),
    sa.Column('notes', sa.Text(), nullable=True, comment='备注'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True, comment='创建时间（可为空，默认NULL）'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True, comment='更新时间（可为空，默认NULL）'),
    sa.PrimaryKeyConstraint('id', name=op.f('biz_agent_symptom_records_pkey'))
    )
    op.create_index(op.f('ix_biz_agent_symptom_records_id'), 'biz_agent_symptom_records', ['id'], unique=False)
    op.create_index(op.f('ix_biz_agent_symptom_records_user_id'), 'biz_agent_symptom_records', ['user_id'], unique=False)
    op.create_index(op.f('ix_biz_agent_symptom_records_start_time'), 'biz_agent_symptom_records', ['start_time'], unique=False)
    
    # 删除LangGraph相关的表（这些表可能不再需要）
    op.drop_table('store_migrations')
    op.drop_table('checkpoint_migrations')
    op.drop_index(op.f('idx_store_expires_at'), table_name='store', postgresql_where='(expires_at IS NOT NULL)')
    op.drop_index(op.f('store_prefix_idx'), table_name='store', postgresql_ops={'prefix': 'text_pattern_ops'})
    op.drop_table('store')
    op.drop_index(op.f('checkpoint_blobs_thread_id_idx'), table_name='checkpoint_blobs')
    op.drop_table('checkpoint_blobs')
    op.drop_index(op.f('checkpoint_writes_thread_id_idx'), table_name='checkpoint_writes')
    op.drop_table('checkpoint_writes')
    op.drop_index(op.f('checkpoints_thread_id_idx'), table_name='checkpoints')
    op.drop_table('checkpoints')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # 删除新创建的表
    op.drop_index(op.f('ix_biz_agent_symptom_records_start_time'), table_name='biz_agent_symptom_records')
    op.drop_index(op.f('ix_biz_agent_symptom_records_user_id'), table_name='biz_agent_symptom_records')
    op.drop_index(op.f('ix_biz_agent_symptom_records_id'), table_name='biz_agent_symptom_records')
    op.drop_table('biz_agent_symptom_records')
    
    op.drop_index(op.f('ix_biz_agent_medication_records_start_date'), table_name='biz_agent_medication_records')
    op.drop_index(op.f('ix_biz_agent_medication_records_user_id'), table_name='biz_agent_medication_records')
    op.drop_index(op.f('ix_biz_agent_medication_records_id'), table_name='biz_agent_medication_records')
    op.drop_table('biz_agent_medication_records')
    
    op.drop_index(op.f('ix_biz_agent_health_event_records_event_date'), table_name='biz_agent_health_event_records')
    op.drop_index(op.f('ix_biz_agent_health_event_records_user_id'), table_name='biz_agent_health_event_records')
    op.drop_index(op.f('ix_biz_agent_health_event_records_id'), table_name='biz_agent_health_event_records')
    op.drop_table('biz_agent_health_event_records')
    
    # 恢复LangGraph相关的表
    op.create_table('checkpoints',
    sa.Column('thread_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('checkpoint_ns', sa.TEXT(), server_default=sa.text("''::text"), autoincrement=False, nullable=False),
    sa.Column('checkpoint_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('parent_checkpoint_id', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('type', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('checkpoint', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('thread_id', 'checkpoint_ns', 'checkpoint_id', name=op.f('checkpoints_pkey'))
    )
    op.create_index(op.f('checkpoints_thread_id_idx'), 'checkpoints', ['thread_id'], unique=False)
    op.create_table('checkpoint_writes',
    sa.Column('thread_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('checkpoint_ns', sa.TEXT(), server_default=sa.text("''::text"), autoincrement=False, nullable=False),
    sa.Column('checkpoint_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('task_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('idx', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('channel', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('type', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('blob', postgresql.BYTEA(), autoincrement=False, nullable=False),
    sa.Column('task_path', sa.TEXT(), server_default=sa.text("''::text"), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('thread_id', 'checkpoint_ns', 'checkpoint_id', 'task_id', 'idx', name=op.f('checkpoint_writes_pkey'))
    )
    op.create_index(op.f('checkpoint_writes_thread_id_idx'), 'checkpoint_writes', ['thread_id'], unique=False)
    op.create_table('checkpoint_blobs',
    sa.Column('thread_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('checkpoint_ns', sa.TEXT(), server_default=sa.text("''::text"), autoincrement=False, nullable=False),
    sa.Column('channel', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('version', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('type', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('blob', postgresql.BYTEA(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('thread_id', 'checkpoint_ns', 'channel', 'version', name=op.f('checkpoint_blobs_pkey'))
    )
    op.create_index(op.f('checkpoint_blobs_thread_id_idx'), 'checkpoint_blobs', ['thread_id'], unique=False)
    op.create_table('store',
    sa.Column('prefix', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('key', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('value', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('expires_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('ttl_minutes', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('prefix', 'key', name=op.f('store_pkey'))
    )
    op.create_index(op.f('store_prefix_idx'), 'store', ['prefix'], unique=False, postgresql_ops={'prefix': 'text_pattern_ops'})
    op.create_index(op.f('idx_store_expires_at'), 'store', ['expires_at'], unique=False, postgresql_where='(expires_at IS NOT NULL)')
    op.create_table('checkpoint_migrations',
    sa.Column('v', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('v', name=op.f('checkpoint_migrations_pkey'))
    )
    op.create_table('store_migrations',
    sa.Column('v', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('v', name=op.f('store_migrations_pkey'))
    )
    # ### end Alembic commands ###

