"""add trace_id field to embedding_records

Revision ID: d0e8b45e7586
Revises: 52d7e028101e
Create Date: 2026-01-23 17:37:59.253076

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd0e8b45e7586'
down_revision: Union[str, Sequence[str], None] = '52d7e028101e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gd2502_embedding_records', sa.Column('trace_id', sa.String(length=100), nullable=True, comment='Trace ID（用于可观测性追踪，关联 Langfuse）'))
    op.create_index(op.f('ix_gd2502_embedding_records_trace_id'), 'gd2502_embedding_records', ['trace_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_gd2502_embedding_records_trace_id'), table_name='gd2502_embedding_records')
    op.drop_column('gd2502_embedding_records', 'trace_id')
    # ### end Alembic commands ###
