"""add user email field

Revision ID: f297d7a76db3
Revises: 
Create Date: 2025-12-16 10:11:53.799418

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f297d7a76db3'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('biz_agent_users',
    sa.Column('id', sa.Integer(), nullable=False, comment='用户ID'),
    sa.Column('username', sa.String(length=100), nullable=False, comment='用户名'),
    sa.Column('phone', sa.String(length=20), nullable=True, comment='手机号'),
    sa.Column('email', sa.String(length=100), nullable=True, comment='邮箱'),
    sa.Column('is_active', sa.Boolean(), nullable=True, comment='是否激活'),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_biz_agent_users_email'), 'biz_agent_users', ['email'], unique=True)
    op.create_index(op.f('ix_biz_agent_users_id'), 'biz_agent_users', ['id'], unique=False)
    op.create_index(op.f('ix_biz_agent_users_phone'), 'biz_agent_users', ['phone'], unique=True)
    op.create_index(op.f('ix_biz_agent_users_username'), 'biz_agent_users', ['username'], unique=True)
    op.create_table('biz_agent_appointments',
    sa.Column('id', sa.Integer(), nullable=False, comment='预约ID'),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='用户ID'),
    sa.Column('department', sa.String(length=100), nullable=False, comment='科室'),
    sa.Column('doctor_name', sa.String(length=100), nullable=True, comment='医生姓名'),
    sa.Column('appointment_time', sa.DateTime(), nullable=False, comment='预约时间'),
    sa.Column('status', sa.Enum('PENDING', 'CONFIRMED', 'COMPLETED', 'CANCELLED', name='appointmentstatus'), nullable=True, comment='预约状态'),
    sa.Column('notes', sa.Text(), nullable=True, comment='备注'),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.ForeignKeyConstraint(['user_id'], ['biz_agent_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_biz_agent_appointments_appointment_time'), 'biz_agent_appointments', ['appointment_time'], unique=False)
    op.create_index(op.f('ix_biz_agent_appointments_id'), 'biz_agent_appointments', ['id'], unique=False)
    op.create_index(op.f('ix_biz_agent_appointments_user_id'), 'biz_agent_appointments', ['user_id'], unique=False)
    op.create_table('biz_agent_blood_pressure_records',
    sa.Column('id', sa.Integer(), nullable=False, comment='记录ID'),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='用户ID'),
    sa.Column('systolic', sa.Integer(), nullable=False, comment='收缩压（高压）'),
    sa.Column('diastolic', sa.Integer(), nullable=False, comment='舒张压（低压）'),
    sa.Column('heart_rate', sa.Integer(), nullable=True, comment='心率'),
    sa.Column('record_time', sa.DateTime(), nullable=False, comment='记录时间'),
    sa.Column('notes', sa.Text(), nullable=True, comment='备注'),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.ForeignKeyConstraint(['user_id'], ['biz_agent_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_biz_agent_blood_pressure_records_id'), 'biz_agent_blood_pressure_records', ['id'], unique=False)
    op.create_index(op.f('ix_biz_agent_blood_pressure_records_record_time'), 'biz_agent_blood_pressure_records', ['record_time'], unique=False)
    op.create_index(op.f('ix_biz_agent_blood_pressure_records_user_id'), 'biz_agent_blood_pressure_records', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_biz_agent_blood_pressure_records_user_id'), table_name='biz_agent_blood_pressure_records')
    op.drop_index(op.f('ix_biz_agent_blood_pressure_records_record_time'), table_name='biz_agent_blood_pressure_records')
    op.drop_index(op.f('ix_biz_agent_blood_pressure_records_id'), table_name='biz_agent_blood_pressure_records')
    op.drop_table('biz_agent_blood_pressure_records')
    op.drop_index(op.f('ix_biz_agent_appointments_user_id'), table_name='biz_agent_appointments')
    op.drop_index(op.f('ix_biz_agent_appointments_id'), table_name='biz_agent_appointments')
    op.drop_index(op.f('ix_biz_agent_appointments_appointment_time'), table_name='biz_agent_appointments')
    op.drop_table('biz_agent_appointments')
    op.drop_index(op.f('ix_biz_agent_users_username'), table_name='biz_agent_users')
    op.drop_index(op.f('ix_biz_agent_users_phone'), table_name='biz_agent_users')
    op.drop_index(op.f('ix_biz_agent_users_id'), table_name='biz_agent_users')
    op.drop_index(op.f('ix_biz_agent_users_email'), table_name='biz_agent_users')
    op.drop_table('biz_agent_users')
    # ### end Alembic commands ###

