"""初始迁移

Revision ID: fb605d274d89
Revises: 
Create Date: 2025-12-11 14:45:11.397992

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import pgvector


# revision identifiers, used by Alembic.
revision: str = 'fb605d274d89'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """升级数据库架构。"""
    # Ensure vector extension exists
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_traces',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.String(length=100), nullable=False),
    sa.Column('step_name', sa.String(length=100), nullable=False),
    sa.Column('inputs', sa.JSON(), nullable=False),
    sa.Column('outputs', sa.JSON(), nullable=False),
    sa.Column('execution_time', sa.Integer(), nullable=False, comment='Execution time in milliseconds'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_traces_id'), 'agent_traces', ['id'], unique=False)
    op.create_index(op.f('ix_agent_traces_session_id'), 'agent_traces', ['session_id'], unique=False)
    op.create_table('chat_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.String(length=100), nullable=False),
    sa.Column('user_id', sa.String(length=100), nullable=True),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_history_id'), 'chat_history', ['id'], unique=False)
    op.create_index(op.f('ix_chat_history_session_id'), 'chat_history', ['session_id'], unique=False)
    op.create_index(op.f('ix_chat_history_user_id'), 'chat_history', ['user_id'], unique=False)
    op.create_table('knowledge_base',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('source', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_knowledge_base_id'), 'knowledge_base', ['id'], unique=False)
    op.create_table('appointments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('doctor_name', sa.String(length=100), nullable=False),
    sa.Column('department', sa.String(length=100), nullable=False),
    sa.Column('appointment_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_appointments_id'), 'appointments', ['id'], unique=False)
    op.create_table('blood_pressure_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('systolic', sa.Integer(), nullable=False),
    sa.Column('diastolic', sa.Integer(), nullable=False),
    sa.Column('heart_rate', sa.Integer(), nullable=False),
    sa.Column('measured_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_blood_pressure_records_id'), 'blood_pressure_records', ['id'], unique=False)
    op.drop_index(op.f('idx_created_at'), table_name='ai_interaction_records')
    op.drop_index(op.f('idx_group_id'), table_name='ai_interaction_records')
    op.drop_index(op.f('idx_status'), table_name='ai_interaction_records')
    op.drop_index(op.f('idx_user_message_id'), table_name='ai_interaction_records')
    op.drop_index(op.f('ix_ai_interaction_records_id'), table_name='ai_interaction_records')
    op.drop_table('ai_interaction_records')
    op.drop_index(op.f('idx_user_id'), table_name='group_members')
    op.drop_index(op.f('idx_user_role'), table_name='group_members')
    op.drop_index(op.f('ix_group_members_id'), table_name='group_members')
    op.drop_table('group_members')
    op.drop_index(op.f('idx_from_user_id'), table_name='messages')
    op.drop_index(op.f('idx_group_created'), table_name='messages')
    op.drop_index(op.f('ix_messages_id'), table_name='messages')
    op.drop_table('messages')
    op.drop_index(op.f('idx_created_by'), table_name='groups')
    op.drop_index(op.f('ix_groups_id'), table_name='groups')
    op.drop_table('groups')
    op.alter_column('users', 'id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='主键ID',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(length=64),
               type_=sa.String(length=50),
               comment=None,
               existing_comment='用户名',
               existing_nullable=False)
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='创建时间',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(op.f('users_user_id_key'), 'users', type_='unique')
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.drop_column('users', 'user_role')
    op.drop_column('users', 'user_id')
    op.drop_column('users', 'updated_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """降级数据库架构。"""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False, comment='更新时间'))
    op.add_column('users', sa.Column('user_id', sa.VARCHAR(length=48), autoincrement=False, nullable=False, comment='用户唯一标识'))
    op.add_column('users', sa.Column('user_role', sa.VARCHAR(length=32), autoincrement=False, nullable=False, comment='用户身份：PATIENT(患者)/DOCTOR(医生)/AI_ASSISTANT(医生AI助手)'))
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.create_unique_constraint(op.f('users_user_id_key'), 'users', ['user_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='创建时间',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'username',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=64),
               comment='用户名',
               existing_nullable=False)
    op.alter_column('users', 'id',
               existing_type=sa.INTEGER(),
               comment='主键ID',
               existing_nullable=False,
               autoincrement=True)
    op.create_table('groups',
    sa.Column('group_id', sa.VARCHAR(length=64), autoincrement=False, nullable=False, comment='群组唯一标识'),
    sa.Column('group_name', sa.VARCHAR(length=128), autoincrement=False, nullable=False, comment='群组名称'),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True, comment='群组描述'),
    sa.Column('created_by', sa.VARCHAR(length=48), autoincrement=False, nullable=False, comment='创建人ID'),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False, comment='创建时间'),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False, comment='更新时间'),
    sa.PrimaryKeyConstraint('id', name=op.f('groups_pkey')),
    sa.UniqueConstraint('group_id', name=op.f('groups_group_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_groups_id'), 'groups', ['id'], unique=False)
    op.create_index(op.f('idx_created_by'), 'groups', ['created_by'], unique=False)
    op.create_table('messages',
    sa.Column('message_id', sa.VARCHAR(length=64), autoincrement=False, nullable=False, comment='消息唯一标识'),
    sa.Column('group_id', sa.VARCHAR(length=64), autoincrement=False, nullable=False, comment='群组ID'),
    sa.Column('from_user_id', sa.VARCHAR(length=48), autoincrement=False, nullable=False, comment='发送人ID'),
    sa.Column('msg_type', sa.VARCHAR(length=32), autoincrement=False, nullable=False, comment='消息类型：TEXT(文本)/IMAGE(图片)/AI_REPLY(AI回复)'),
    sa.Column('msg_content', sa.TEXT(), autoincrement=False, nullable=False, comment='消息内容'),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False, comment='创建时间'),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False, comment='更新时间'),
    sa.PrimaryKeyConstraint('id', name=op.f('messages_pkey')),
    sa.UniqueConstraint('message_id', name=op.f('messages_message_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_messages_id'), 'messages', ['id'], unique=False)
    op.create_index(op.f('idx_group_created'), 'messages', ['group_id', 'created_at'], unique=False)
    op.create_index(op.f('idx_from_user_id'), 'messages', ['from_user_id'], unique=False)
    op.create_table('group_members',
    sa.Column('group_id', sa.VARCHAR(length=64), autoincrement=False, nullable=False, comment='群组ID'),
    sa.Column('user_id', sa.VARCHAR(length=48), autoincrement=False, nullable=False, comment='用户ID'),
    sa.Column('user_role', sa.VARCHAR(length=32), autoincrement=False, nullable=False, comment='用户在群组中的身份标签：PATIENT/DOCTOR/AI_ASSISTANT'),
    sa.Column('joined_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False, comment='加入时间'),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False, comment='创建时间'),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False, comment='更新时间'),
    sa.PrimaryKeyConstraint('id', name=op.f('group_members_pkey')),
    sa.UniqueConstraint('group_id', 'user_id', name=op.f('uk_group_user'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_group_members_id'), 'group_members', ['id'], unique=False)
    op.create_index(op.f('idx_user_role'), 'group_members', ['user_role'], unique=False)
    op.create_index(op.f('idx_user_id'), 'group_members', ['user_id'], unique=False)
    op.create_table('ai_interaction_records',
    sa.Column('record_id', sa.VARCHAR(length=64), autoincrement=False, nullable=False, comment='记录唯一标识'),
    sa.Column('group_id', sa.VARCHAR(length=64), autoincrement=False, nullable=False, comment='群组ID'),
    sa.Column('user_message_id', sa.VARCHAR(length=64), autoincrement=False, nullable=False, comment='用户消息ID'),
    sa.Column('ai_message_id', sa.VARCHAR(length=64), autoincrement=False, nullable=True, comment='AI回复消息ID'),
    sa.Column('ai_service_url', sa.VARCHAR(length=256), autoincrement=False, nullable=True, comment='AI服务URL'),
    sa.Column('request_content', sa.TEXT(), autoincrement=False, nullable=True, comment='请求内容（JSON格式）'),
    sa.Column('response_content', sa.TEXT(), autoincrement=False, nullable=True, comment='响应内容（JSON格式）'),
    sa.Column('status', sa.INTEGER(), autoincrement=False, nullable=False, comment='状态：0-处理中，1-成功，2-失败'),
    sa.Column('duration_ms', sa.BIGINT(), autoincrement=False, nullable=True, comment='处理耗时（毫秒）'),
    sa.Column('error_message', sa.VARCHAR(length=500), autoincrement=False, nullable=True, comment='错误信息'),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False, comment='创建时间'),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False, comment='更新时间'),
    sa.PrimaryKeyConstraint('id', name=op.f('ai_interaction_records_pkey')),
    sa.UniqueConstraint('record_id', name=op.f('ai_interaction_records_record_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_ai_interaction_records_id'), 'ai_interaction_records', ['id'], unique=False)
    op.create_index(op.f('idx_user_message_id'), 'ai_interaction_records', ['user_message_id'], unique=False)
    op.create_index(op.f('idx_status'), 'ai_interaction_records', ['status'], unique=False)
    op.create_index(op.f('idx_group_id'), 'ai_interaction_records', ['group_id'], unique=False)
    op.create_index(op.f('idx_created_at'), 'ai_interaction_records', ['created_at'], unique=False)
    op.drop_index(op.f('ix_blood_pressure_records_id'), table_name='blood_pressure_records')
    op.drop_table('blood_pressure_records')
    op.drop_index(op.f('ix_appointments_id'), table_name='appointments')
    op.drop_table('appointments')
    op.drop_index(op.f('ix_knowledge_base_id'), table_name='knowledge_base')
    op.drop_table('knowledge_base')
    op.drop_index(op.f('ix_chat_history_user_id'), table_name='chat_history')
    op.drop_index(op.f('ix_chat_history_session_id'), table_name='chat_history')
    op.drop_index(op.f('ix_chat_history_id'), table_name='chat_history')
    op.drop_table('chat_history')
    op.drop_index(op.f('ix_agent_traces_session_id'), table_name='agent_traces')
    op.drop_index(op.f('ix_agent_traces_id'), table_name='agent_traces')
    op.drop_table('agent_traces')
    # ### end Alembic commands ###
