"""add user table

Revision ID: 29f1fe57ef5b
Revises: 92b773e90bb2
Create Date: 2026-01-05 13:59:29.512343

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '29f1fe57ef5b'
down_revision: Union[str, Sequence[str], None] = '92b773e90bb2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gd2502_users',
    sa.Column('id', sa.String(length=50), nullable=False, comment='用户ID（ULID）'),
    sa.Column('user_name', sa.String(length=100), nullable=False, comment='用户名（唯一）'),
    sa.Column('user_info', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='用户信息（JSON格式）'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间（自动生成）'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True, comment='更新时间（自动更新）'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gd2502_users_id'), 'gd2502_users', ['id'], unique=False)
    op.create_index(op.f('ix_gd2502_users_user_name'), 'gd2502_users', ['user_name'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_gd2502_users_user_name'), table_name='gd2502_users')
    op.drop_index(op.f('ix_gd2502_users_id'), table_name='gd2502_users')
    op.drop_table('gd2502_users')
    # ### end Alembic commands ###
