"""init schema with gd2502 prefix

Revision ID: 92b773e90bb2
Revises: 
Create Date: 2026-01-05 11:21:16.413932

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '92b773e90bb2'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gd2502_blood_pressure_records',
    sa.Column('id', sa.String(length=50), nullable=False, comment='记录ID（ULID）'),
    sa.Column('user_id', sa.String(length=50), nullable=False, comment='用户ID'),
    sa.Column('systolic', sa.Integer(), nullable=False, comment='收缩压（高压，单位：mmHg）'),
    sa.Column('diastolic', sa.Integer(), nullable=False, comment='舒张压（低压，单位：mmHg）'),
    sa.Column('heart_rate', sa.Integer(), nullable=True, comment='心率（单位：bpm，可选）'),
    sa.Column('record_time', sa.DateTime(timezone=True), nullable=True, comment='记录时间（可选）'),
    sa.Column('notes', sa.Text(), nullable=True, comment='备注（可选）'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间（自动生成）'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True, comment='更新时间（自动更新）'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gd2502_blood_pressure_records_id'), 'gd2502_blood_pressure_records', ['id'], unique=False)
    op.create_index(op.f('ix_gd2502_blood_pressure_records_record_time'), 'gd2502_blood_pressure_records', ['record_time'], unique=False)
    op.create_index(op.f('ix_gd2502_blood_pressure_records_user_id'), 'gd2502_blood_pressure_records', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_gd2502_blood_pressure_records_user_id'), table_name='gd2502_blood_pressure_records')
    op.drop_index(op.f('ix_gd2502_blood_pressure_records_record_time'), table_name='gd2502_blood_pressure_records')
    op.drop_index(op.f('ix_gd2502_blood_pressure_records_id'), table_name='gd2502_blood_pressure_records')
    op.drop_table('gd2502_blood_pressure_records')
    # ### end Alembic commands ###
